### ISSUE TITLE
stl import

### ISSUE THREAD

**Issue by t4rj4n** [jay3sh/cadmium#2]
Hallo,

i dont know if it is possible to import an stl and use it a primive.
I tried to do it but keep getting a runtime exception in line "
test = sol + s0":

"Message    File Name   Line    Position  
Traceback  
    <module>    C:\Documents and Settings\Tarjan\My Documents\Downloads\jayesh3-cadmium-ff4e994\jayesh3-cadmium-ff4e994\examples\example-001b.py    21  
    **add** c:\Python26\Lib\site-packages\cadmium\solid.py  42  
RuntimeError: StdFail_NotDone
BRep_API: command not done              "

My Code is:
# !/usr/bin/python

import sys
import math
sys.path.append('./src')

from cadmium import *

stlfname = "example.stl"#sys.argv[1]

s0 = Sphere(r=4)

from OCC.Utils.DataExchange import STL
reader = STL.STLImporter(r'basebrick.stl')
reader.read_file()

sol = Solid(reader.get_shape())

test = sol + s0

test.toSTL(stlfname)

---

If somebody tells me how, ican upload the stl file. It seems that the OpenCASCADE lib throws the exception. But i cant step into it...

Tarjan

**Comment by jay3sh** [comment]
Hi Tarjan,

Cadmium is not designed to work with imported STLs (even though OpenCASCADE can import shapes from STLs). Not all shapes can be used as primitives and operated on by CSG boolean operators. The solids used in boolean operations have to be closed solids and any arbitrary BREP imported from STL won't be guaranteed to be a closed solid.

OpenCASCADE (and pythonOCC), is generic solid modeling library whose scope extends beyond CSG operations, therefore they have STL import functionality (among other data exchange formats), but cadmium is limited to CSG operations only (at least so far), therefore it doesn't support STL import. Cadmium's main goal is to make 3D printable solids, for which close-ness is a necessary condition.

Hope that helps.

**Comment by t4rj4n** [comment]
I understand that,

so I wouldnt mind if you dont want to give further answers, but such a feature would be very nice in my opinion.

Not every primitve is constructed of primitives but are created in some other 3d modeling package.

And if only a closed primitive can be used, how do i check that (primitive.shape.Closed() return 16?) and if not how do i close them. The stl file im using is closed at least i cant see any holes (is was created from a cube with subdivision surface refinement).

I will try to get docu for pythonOCC and OpenCascade...

By the way. I tried OpenScad for my Project but that seems to be awfull slow. Thats when ive found Cadmium.

Greetings

Tarjan

**Comment by jay3sh** [comment]
## 

Jayesh
http://www.3dtin.com
Twitter: @3dtin
Facebook: http://www.facebook.com/3DTin

On Wed, Oct 26, 2011 at 8:56 PM, t4rj4n <
reply@reply.github.com>wrote:

> I understand that,
> 
> so I wouldnt mind if dont want to give further answers, but such feature
> would be very nice in my opinion.

To my knowledge, the primitives for CSG are meant to be handful and not any
arbitrary shapes. I would suggest this article about CSG modeling
http://en.wikipedia.org/wiki/Constructive_solid_geometry

The primitives are typically a small set of shapes whose geometry can be
well defined. To define any arbitrary shape one needs to use BREP (e.g.
faces, edges, vertices,etc.), which is not the ideal geometry, but its
approximation. I am not sure about CSG implementation algorithms, but I can
imagine that applying boolean operation algorithms on such approximate data
structures will not guarantee closeness in resulting solids.

However I am not absolutely sure about working of OpenCASCADE. I intend to
study this topic further in near future to explore possible enhancements to
cadmium. Stay tuned.

> Not every primitve is constructed of primitives but are created in some
> other 3d modeling package.
> 
> And if only a closed primitive can be used, how do i check that
> (primitive.shape.Closed() return 16?) and if not how do i close them. The
> stl file im using is closed at least i cant see any holes (is was created
> from a cube with subdivision surface refinement).

One cannot rely on visual inspection for detecting holes in BREP. The holes
can get generated by floating point errors too.

I didn't know if there was a shape.Closed() check in OpenCASCADE, I will
look into it.
